var myString;
var myNumber;
var myBoolean;
var myVariable;
var stringArray; // let stringArray: Array<string>;
var numberArray; // let numberArray: Array<number>;
var booleanArray; // let booleanArray: Array<boolean>;
var stringNumberTuple;
// let myVoid: void = null;
var myVoid = undefined;
var myNull = null;
var myUndefined = undefined;
myString = "Hello From TypeScript";
myNumber = 1;
myBoolean = false;
myVariable = 123 + "test";
stringArray = ["Hello", "World"];
numberArray = [1, 2, 3, 4, 5, 6, 7, 8, 9];
booleanArray = [true, false];
stringNumberTuple = ["hey", 100];
console.log(myString);
console.log(myNumber);
console.log(myBoolean);
console.log(myVariable);
console.log(stringArray);
console.log(numberArray);
console.log(booleanArray);
console.log(stringNumberTuple);
console.log(myVoid);
console.log(myNull);
console.log(myUndefined);
